# INFO6105 Instructor: Dr. Handan Liu
Homework 1  
Signed on 2020/01/23
Submitted by the end of 2020/01/30 on Blackboard. The late submission will be accepted up to one day after the deadline with a 50% penalty according to the policy in the syllabus.

Grading: total 100 points.

# **1. Create Numpy Arrays:  total 28 points**


In [2]:
import numpy as np

**1) Create an array of [1, 2, 3].    - 1 point**


In [6]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


**2) Let x = [1, 2]. Convert it into an array.  - 1 point**


In [11]:
x = [1, 2]
print(x)
print(type(x))

[1, 2]
<class 'list'>


In [17]:
np.array(x)

array([1, 2])

In [19]:
print(type(np.array(x)))

<class 'numpy.ndarray'>


**3) Create a new array of 3 x 2 float numbers, filled with ones.  - 1 point**

In [39]:
arrOnes = np.ones([3,2],dtype=float)

In [40]:
arrOnes

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

**4) Create a 3-D array with ones on the diagonal and zeros elsewhere.  - 1 point**

In [42]:
import numpy as np
ex3 = np.eye(3,3)
print(ex3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**5) Create a new array of 2 x 5 uints, filled with 6.   - 2 point**

In [3]:
full=np.full((2,5),6)
print(full)

[[6 6 6 6 6]
 [6 6 6 6 6]]


**6) Create an array of 2, 4, 6, 8, ..., 98, 100.   - 2 point**

In [6]:
arrayEven = np.arange(2,101,2)
print(arrayEven)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


**7) create an array of 10 zeros; another array of 10 fives. - 2 points**

In [8]:
#Array of 10 zeros
arrZeros = np.zeros((10))
print(arrZeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
#Array of 10 fives
arrFives = np.ones(10)*5
print(arrFives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**8) create a 3x3x3 array filled with arbitrary values. - 2 points**

In [9]:
x = np.random.random((3,3,3))
print(x)

[[[0.96503636 0.21086994 0.25866994]
  [0.64745067 0.94783997 0.95184505]
  [0.01728592 0.30354361 0.25153887]]

 [[0.20250417 0.90102677 0.56547601]
  [0.66476106 0.487956   0.8176733 ]
  [0.16669076 0.47654569 0.55909706]]

 [[0.98490813 0.41323813 0.10764012]
  [0.83514817 0.68341791 0.31735992]
  [0.30651933 0.5184885  0.73152601]]]


**9) create a 3x4 matrix filled with values from 10 to 21 (inclusive). - 6 ponits**

In [11]:
p = np.arange(10,22).reshape((3,4))
print(p)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


**10) Create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. Please use the numpy "slicing" method to realize.**
     - 10 points

In [13]:
m = np.zeros((4,4))
m[::2,1::2]=1
m[1::2,::2]=1
print(m)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


# **2. Numpy Randm Number  - total 8 points**
    - 4 points


**1) Assign number 10 to the seed of the random generator so that you can get the same value next time.   - 2 point**

In [83]:
import random
print ("Random number with seed 10")
random.seed( 10 )
print ("First random value- ", random.randint(25,50))

random.seed( 10 )
print ("Second random value- ", random.randint(25,50))

random.seed( 20 )
print ("Different random value- ", random.randint(25,50))

Random number with seed 10
First random value-  43
Second random value-  43
Different random value-  48


**2) Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).  - 2 point**

In [45]:
xy = np.random.uniform(0, 1, size = (3,2))
print(xy)

[[0.51814647 0.49849209]
 [0.5289514  0.65183359]
 [0.94549513 0.83773745]]


**3) Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.** 

In [47]:
intxy = np.random.randint(4,size=(3,2))
print(intxy)

[[3 0]
 [2 0]
 [0 3]]


# 3. Operate on Numpy Arrays: total 23 points


**1) Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order. - 4 points**

In [48]:
z = np.arange(1,10)
print("Original Array: ",z)
print("After Spliting in 4,2 and 3 elements: ")
print(np.split(z,[4,6]))

Original Array:  [1 2 3 4 5 6 7 8 9]
After Spliting in 4,2 and 3 elements: 
[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


**2) Given an array    - 8 points
[[ 0., 1., 2., 3.],
[ 4., 5., 6., 7.],
[ 8., 9., 10., 11.],
[ 12., 13., 14., 15.]].
Split it into two arrays along the second axis.**

In [50]:
n = np.arange(16).reshape((4, 4))
print("Original array:",n)
print("After splitting horizontally:")
print(np.hsplit(n, [2]))

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


**3) Given an array: [[5,10,15],[20,25,30],[35,40,45]]   - 4 points
(1) Slicing to get the sub-array [[10,15],[25,30]]
(2) Getting individual element value "20"**

In [64]:
x=np.arange(5,50,5).reshape(3,3)
x

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

**(1) Slicing to get the sub-array [[10,15],[25,30]]**

In [65]:
print(x[0:2,1:3])

[[10 15]
 [25 30]]


**(2) Getting individual element value "20"**

In [66]:
x[1:2,0:1]

array([[20]])

**4)  - 6 points
Let x be an array**
[[ 1 2 3]
 [ 4 5 6]].

and y be an array
[[ 7 8 9]
 [10 11 12]].

Concatenate x and y so that a new array looks like
[[1, 2, 3, 7, 8, 9],
 [4, 5, 6, 10, 11, 12]].

In [32]:
x = np.arange(1,7).reshape(2,3)
print(x)

[[1 2 3]
 [4 5 6]]


In [33]:
y = np.arange(7,13).reshape(2,3)
print(y)

[[ 7  8  9]
 [10 11 12]]


In [34]:
#Concatenate x and y to get a new array
z = np.concatenate([x,y], axis=1)
print("Concatenated Array is :",z)

Concatenated Array is : [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# 4. Array Slicing: total 10 points, 2 points each
Given an array: 
array([ 3,  6,  9,  25, 10,  8])


In [55]:
arrnew = np.array([ 3,  6,  9,  25, 10,  8])
print(arrnew)

[ 3  6  9 25 10  8]


**1) To get all elements except the first:**

In [56]:
arrnew[1:]

array([ 6,  9, 25, 10,  8])

**2) To get all elements except the last:**

In [57]:
arrnew[:5]

array([ 3,  6,  9, 25, 10])

**3) To get every other element of the array (operation from the first element):**

In [60]:
arrnew[::2]

array([ 3,  9, 10])

**4) To get every element of the array (operation from the second element):**

In [62]:
arrnew[1::]

array([ 6,  9, 25, 10,  8])

**5) To reverse the array:**

In [63]:
arrnew[::-1]

array([ 8, 10, 25,  9,  6,  3])

# 5. Multidimensional Arrays: total 4 points, 1 points each


**1) create an array with the components as 0-31 and the shape is (8,4)**

In [53]:
arrMulti = np.arange(32).reshape(8,4)
print(arrMulti)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


**2) set the 3rd element in the 1st row to 0**

In [54]:
arrMulti[0,2]=0
print(arrMulti)

[[ 0  1  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


**3)  the second column**

In [55]:
print(arrMulti[:,1])

[ 1  5  9 13 17 21 25 29]


**4) select any 3x3 region from the array**

In [62]:
print(arrMulti[2:5,1:5])

[[ 9 10 11]
 [13 14 15]
 [17 18 19]]


# 6. Create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.   - 7 points

And print the formatted outputs which keep 5 digits after the decimal point.


In [35]:
import numpy as np
arrY = np.random.random(1000).round(5)
print("Original Array: ",arrY)

Original Array:  [7.5909e-01 4.0399e-01 2.8157e-01 1.8004e-01 8.5407e-01 2.8153e-01
 8.9685e-01 1.0819e-01 7.4045e-01 9.8807e-01 1.5675e-01 1.6710e-01
 4.3597e-01 7.0558e-01 2.5227e-01 8.6170e-02 2.1307e-01 2.4935e-01
 8.7252e-01 2.4394e-01 6.5586e-01 5.6706e-01 4.7310e-02 5.0110e-02
 2.2305e-01 3.4970e-01 1.1516e-01 7.2387e-01 4.8200e-01 3.0088e-01
 5.9532e-01 9.3884e-01 3.5121e-01 3.0197e-01 5.6430e-01 1.1936e-01
 9.0888e-01 5.4564e-01 8.0246e-01 2.8017e-01 2.4793e-01 6.6114e-01
 2.9043e-01 9.7579e-01 6.6783e-01 9.8317e-01 1.5662e-01 9.5431e-01
 6.4024e-01 5.4796e-01 6.0793e-01 2.0108e-01 1.9831e-01 7.0813e-01
 8.8057e-01 6.6153e-01 3.7080e-02 2.8098e-01 3.9686e-01 9.1758e-01
 9.3380e-02 8.3580e-02 3.3860e-02 3.3398e-01 5.6788e-01 8.4719e-01
 8.0797e-01 7.7297e-01 5.1320e-01 3.0500e-02 4.8341e-01 4.5644e-01
 6.6349e-01 3.0330e-01 3.8220e-01 6.6400e-01 2.5111e-01 4.7939e-01
 9.7174e-01 7.9969e-01 2.1635e-01 1.5469e-01 3.1656e-01 3.5870e-02
 1.8700e-01 6.6242e-01 1.2037e-01 1.2842e-01 

In [36]:
avgr = arrY.mean()
print("Average: %0.5f" % avgr)

Average: 0.50286


In [37]:
std = arrY.std()
print("Standard deviation: %0.5f" % std)

Standard deviation: 0.29190


In [38]:
var = arrY.var()
print("Variance:%0.5f" % var)

Variance:0.08521


# 7. Broadcasting: 10 points

1) Please add the following two arrays according to the 3 rules. You can reshape the array by np.reshape or 'newaxis'. (each for 5 points)

**1) 
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])**


In [68]:
import numpy as np 
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

In [69]:
b[:,np.newaxis].shape
b[:,np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [72]:
add =a+b[:,np.newaxis]
add

array([[ 1., 11., 21., 31.],
       [ 2., 12., 22., 32.],
       [ 3., 13., 23., 33.]])

**2) 
x = np.arange(4)
y = np.ones(5)**


In [76]:
x = np.arange(4)
y = np.ones(5)

In [77]:
x

array([0, 1, 2, 3])

In [78]:
y

array([1., 1., 1., 1., 1.])

In [79]:
y[:,np.newaxis]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [80]:
x+y[:,np.newaxis]

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

# 8. Write a 6x6 times table matrix:  total 10 points 
    - by using numpy broadcasting (5 points) 
    - by using Python nested for-loop (5 points).
    

Numpy Broadcasting

In [84]:
table = np.arange(1,7)
table

array([1, 2, 3, 4, 5, 6])

In [85]:
table2 = table[:,np.newaxis]
table2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [88]:
broadcast = table * table2
broadcast

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

Python nested for-loop

In [89]:
table

array([1, 2, 3, 4, 5, 6])

In [91]:
leng = len(table)
leng

6

In [92]:
val = np.empty((leng,leng),dtype = int, order = 'C')

In [94]:
for i, m in enumerate(table):
    for j, n in enumerate(table):
        val[i,j] = m*n
print(val)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
